server:
  prot: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: lzx0203.
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
      type-aliases-package: com.example.springboot_login.entity  # 注意：对应实体类的路径
